name: Build and deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: trepsi-v5-dev
  ACCOUNT: cicd-github@trepsi-v5-dev.iam.gserviceaccount.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          service_account: ${{ env.ACCOUNT }}
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "docker login"
        run: gcloud auth configure-docker

      - name: "build docker"
        run: docker build -t gcr.io/${{ env.PROJECT_ID }}/test1:${{github.sha}} .

      - name: "push"
        run: docker push gcr.io/${{ env.PROJECT_ID }}/test1:${{github.sha}}
